---
inventory: nornir.plugins.inventory.simple.SimpleInventory
SimpleInventory:
    host_file: "transforming_inventory_data/inventory/hosts.yaml"
    group_file: "transforming_inventory_data/inventory/groups.yaml"
transform_function: "transforming_inventory_data.helpers.adapt_host_data"
