---
host1.cmh:
    site: cmh
    role: host
    group: cmh-host
    nos: linux

host2.cmh:
    site: cmh
    role: host
    group: cmh-host
    nos: linux

switch00.cmh:
    brigade_ip: 127.0.0.1
    brigade_username: vagrant
    brigade_password: vagrant
    napalm_port: 12443
    site: cmh
    role: leaf
    group: cmh-leaf
    nos: eos

switch01.cmh:
    brigade_ip: 127.0.0.1
    brigade_username: vagrant
    brigade_password: ""
    napalm_port: 12203
    site: cmh
    role: leaf
    group: cmh-leaf
    nos: junos

host1.bma:
    site: bma
    role: host
    group: bma-host
    nos: linux

host2.bma:
    site: bma
    role: host
    group: bma-host
    nos: linux

switch00.bma:
    brigade_ip: 127.0.0.1
    brigade_username: vagrant
    brigade_password: vagrant
    napalm_port: 12443
    site: bma
    role: leaf
    group: bma-leaf
    nos: eos

switch01.bma:
    brigade_ip: 127.0.0.1
    brigade_username: vagrant
    brigade_password: ""
    napalm_port: 12203
    site: bma
    role: leaf
    group: bma-leaf
    nos: junos
