---
host1.cmh:
    site: cmh
    role: host
    group: cmh
    brigade_nos: linux
    type: host

host2.cmh:
    site: cmh
    role: host
    group: cmh
    brigade_nos: linux
    type: host

spine00.cmh:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: vagrant
    brigade_network_api_port: 12444
    site: cmh
    role: spine
    group: cmh
    brigade_nos: eos
    type: network_device

spine01.cmh:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: ""
    brigade_network_api_port: 12204
    site: cmh
    role: spine
    group: cmh
    brigade_nos: junos
    type: network_device

leaf00.cmh:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: vagrant
    brigade_network_api_port: 12443
    site: cmh
    role: leaf
    group: cmh
    brigade_nos: eos
    type: network_device

leaf01.cmh:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: ""
    brigade_network_api_port: 12203
    site: cmh
    role: leaf
    group: cmh
    brigade_nos: junos
    type: network_device

host1.bma:
    site: bma
    role: host
    group: bma
    brigade_nos: linux
    type: host

host2.bma:
    site: bma
    role: host
    group: bma
    brigade_nos: linux
    type: host

spine00.bma:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: vagrant
    brigade_network_api_port: 12444
    site: bma
    role: spine
    group: bma
    brigade_nos: eos
    type: network_device

spine01.bma:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: ""
    brigade_network_api_port: 12204
    site: bma
    role: spine
    group: bma
    brigade_nos: junos
    type: network_device

leaf00.bma:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: vagrant
    brigade_network_api_port: 12443
    site: bma
    role: leaf
    group: bma
    brigade_nos: eos
    type: network_device

leaf01.bma:
    brigade_host: 127.0.0.1
    brigade_username: vagrant
    brigade_password: ""
    brigade_network_api_port: 12203
    site: bma
    role: leaf
    group: bma
    brigade_nos: junos
    type: network_device
